# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/huawei/hi6250-8-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter prague warsaw,$(TARGET_DEVICE)),)

endif
